root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "docs"]
  delay = 300
  stop_on_error = true

[log]
  time = true
